### ISSUE TITLE
Typehinting properties not working

### ISSUE THREAD

**Issue by FlickerBean** [epii1/phpcd.vim#189]
I think this one is best explained with an example:

```
<?php

use App\Services\MyHelperService;

class Service
{
    /**
     * @var MyHelperService $helperService
     * /
    protected MyHelperService $helperService; // <-- Removing the typehint 'MyHelperService' from the line resolves the problem

    public function __construct(
        MyHelperService $helperService
    ) {
        $this->helperService = $helperService;
    }

    public function doSomething()
    {
        $this-> // No auto completion results
    }
````

**Comment by lvht** [comment]
Hi @FlickerBean , I am very happy that phpcd.vim will help your php development.

The long-waiting property typehint feature has been introduced in PHP8.0. And phpcd.vim used the BetterReflection to inspect php code information. However, the BetterReflection does not support PHP8 now. Please see https://github.com/Roave/BetterReflection/issues/701

Once the BetterReflection supports PHP8, I will upgrade phpcd.vim.

**Comment by FlickerBean** [comment]
Hi! @lvht 

Thanks for getting back to me!

Totally understand, but this is a PHP 7.4 feature:

https://wiki.php.net/rfc/typed_properties_v2

**Comment by lvht** [comment]
@FlickerBean sorry for misleading. It seems this feature has been implemented in https://github.com/lvht/phpcd.vim/commit/d1532efa2f2c808b7a3a0f83aa9826e460941c96

Maybe it has some bug.

**Comment by lvht** [comment]
Please try https://github.com/lvht/phpcd.vim/commit/f2c9e0673cbb40c496b3965690c1e17e6ab11d32

**Comment by FlickerBean** [comment]
Unfortunately this still hasn't solved the issue :(

**Comment by epii1** [comment]
ensure `MyHelperService` could be autoloaded by phpcd(composer or customer autoload php script)

**Comment by FlickerBean** [comment]
It can, and it works if I remove the type-hint from the property definition.

**Comment by epii1** [comment]
@FlickerBean thanks for feedbacking, and here are the debugging process. It's a bug.

[![asciicast](https://asciinema.org/a/ztd0cin7U6I2ixTn6cbGQ7j43.svg)](https://asciinema.org/a/ztd0cin7U6I2ixTn6cbGQ7j43)

**Comment by epii1** [comment]
And here is the problem https://www.php.net/manual/en/class.reflectiontype.php#124658

**Comment by epii1** [comment]
Hi @FlickerBean  would you like to join maintaining phpcd.vim?

I seldom do php programming(now using go mostly) since 2018. It is hard for me to do quick response to issue or new feature.

**Comment by epii1** [comment]
@FlickerBean You have said
> Having multiple vims open per project would go against the way I've used vim for the last 10+ years!

I have to say "me, too" 😄 

When I start phpcd.vim, I wish to reimplement all phpcomplete's feature by pure php code. So that every php programmer could contribute to this plugin.

Now look back the pass six years, there is too seldom php programmer have the ability to improve phpcd's code.

If you have the ability, I wish you could join the maintenance.

**Comment by FlickerBean** [comment]
Hi @epii1 

I haven't looked into the codebase, I'm certainly happy to provide fixes/improvements where time allows. But time is a major constraint, as I'm sure it is for you also!
